<meta charset="gbk">
<meta name="robots" content="all">
<meta name="author" content="Tencent-CP">
<meta name="Copyright" content="Tencent">
<meta itemprop="name" content="真龙霸业官方网站"/>
<meta itemprop="image" content="https://game.gtimg.cn/images/3new/web201712/qqshare.png" />
<meta name="description" itemprop="description" content="《真龙霸业》手游12月12日全平台预约火热开启，平乱世，争天下，想体验不一样的三国么，《真龙霸业》等你来战！" />
<meta name="Keywords" content="真龙霸业，真龙霸业官网，腾讯真龙霸业，真龙霸业礼包，真龙霸业下载，三国，权谋，武将，策略战斗，策略，策略手游" />
<meta name="Description" content="《真龙霸业》手游12月12日全平台预约火热开启，平乱世，争天下，想体验不一样的三国么，《真龙霸业》等你来战！" />
<!-- 页面设计：微聚cp | 页面制作：微聚cp | 创建：2018-04-12 -->
