<!-- 顶部导航 -->
<header class="top">
    <h1 class="top-logo fl"><a href="###"><img class="top-logo-img" src="ossweb-img/logo.png" alt="三国群英传"></a></h1>
    <section class="top-decr fl">
        <h2 class="top-decr-text1">真龙霸业</h2>
        <h3 class="top-decr-text2">腾讯策略手游匠心巨制</h3>
    </section>
    <a class="top-order fl spr" href="###">立即预约</a>
    <ul class="top-menu fr spr">
        <li class="top-menu-bar top-menu-bar1"></li>
        <li class="top-menu-bar top-menu-bar2"></li>
        <li class="top-menu-bar top-menu-bar3"></li>
    </ul>
</header>
<!-- 菜单 -->
<nav id="commonNav" class="common-nav" >
    <div class="cover-content">
        <ul>
            <li><a ontouchend="PTTSendClick('banner','link1','首页')" href="">首页</a></li>
            <li><a ontouchend="PTTSendClick('banner','link2','新闻资讯')" href="">新闻资讯</a></li>
            <li><a ontouchend="PTTSendClick('banner','link3','游戏攻略')" href="">游戏攻略</a></li>
            <li><a ontouchend="PTTSendClick('banner','link4','CDKEY')" href="">CDKEY</a></li>
            <!--<li><a ontouchend="PTTSendClick('banner','link5','预约礼包')" href="//bwzy.qq.com/cp/a20170904yym/index.htm">预约礼包</a></li>-->
            <li><a ontouchend="PTTSendClick('banner','link6','官方论坛')" href="">官方论坛</a></li>
        </ul>
    </div>
</nav>