<meta charset="gbk">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
<meta name="robots" content="all">
<meta name="applicable-device" content="mobile">
<meta name="format-detection" content="telephone=no">
<meta name="msapplication-tap-highlight" content="no">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta content="email=no" name="format-detection">
<meta name="Keywords" content="真龙霸业，真龙霸业官网，腾讯真龙霸业，真龙霸业礼包，真龙霸业下载，三国，权谋，武将，策略战斗，策略，策略手游" />
<meta name="Description" content="《真龙霸业》手游12月12日全平台预约火热开启，平乱世，争天下，想体验不一样的三国么，《真龙霸业》等你来战！" />
<link rel="stylesheet" href="css/common.css">
<script>
    (function (win,doc){
        if (!win.addEventListener) return;
        var html=document.documentElement;
        function setFont()
        {
            var cliWidth=html.clientWidth;
            html.style.fontSize=100*(cliWidth/750)+'px';
        }
        win.addEventListener('resize',setFont,false);
        setFont();
    })(window,document);
</script>